name: json_to_soal_parser
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_tex: ^4.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_text_field: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
