name: json_to_soal_parser
description: "A new Flutter project."
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_riverpod: ^2.5.1
  flutter_tex: ^4.0.6
  freezed_annotation: ^2.4.1
  go_router: ^14.2.1
  http: ^1.2.2
  json_annotation: ^4.8.1
  json_text_field: ^1.2.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  package_info_plus: ^8.0.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
